---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        # THIS IS AN GITHUB SUPPORTED ACTION
        # THAT FACILITATES THE LOG IN TO DOCKERHUB
        uses: docker/login-action@v1
        # OUR REPOs SECRETS
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # This checks out the code to inside the job
      - name: Checkout
        uses: actions/checkout@v2
      # Runs test suit
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
